# Metadata.
unstable_features = true

# Braces.
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

# Functions.
empty_item_single_line = true
fn_single_line = true
format_macro_matchers = true
format_macro_bodies = true

# Indentation.
indent_style = "Visual"


# Comments.
wrap_comments = true
