name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Format code (rustfmt)
      run: cargo fmt --all
    - name: Push format changes
      run: | 
        if [[ $(git diff --stat) != '' ]]; then
          git config --global user.name 'GitHub Actions'
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Automated formatting"
          git push
        fi
